import type { PluginDef } from '#shared/types/svgo';

export const PLUGIN_DEFS: PluginDef[] = [
  // Metadata & document
  {
    name: 'removeDoctype',
    label: 'Remove doctype',
    description: 'Removes the DOCTYPE declaration',
    defaultEnabled: true,
    category: 'metadata',
  },
  {
    name: 'removeXMLProcInst',
    label: 'Remove XML instructions',
    description: 'Removes XML processing instructions',
    defaultEnabled: true,
    category: 'metadata',
  },
  {
    name: 'removeXMLNS',
    label: 'Remove xmlns',
    description: 'Removes the xmlns attribute (for inline SVG)',
    defaultEnabled: false,
    category: 'metadata',
  },
  {
    name: 'removeComments',
    label: 'Remove comments',
    description: 'Removes XML comments',
    defaultEnabled: true,
    category: 'metadata',
  },
  {
    name: 'removeMetadata',
    label: 'Remove <metadata>',
    description: 'Removes <metadata> elements',
    defaultEnabled: true,
    category: 'metadata',
  },
  {
    name: 'removeEditorsNSData',
    label: 'Remove editor data',
    description: 'Removes editor namespaces, elements, and attributes',
    defaultEnabled: true,
    category: 'metadata',
  },
  {
    name: 'removeDeprecatedAttrs',
    label: 'Remove deprecated attributes',
    description: 'Removes attributes that are deprecated in SVG',
    defaultEnabled: true,
    category: 'metadata',
  },
  {
    name: 'removeUnusedNS',
    label: 'Remove unused namespaces',
    description: 'Removes unused namespace declarations',
    defaultEnabled: true,
    category: 'metadata',
  },

  // Styles
  {
    name: 'cleanupAttrs',
    label: 'Clean up attribute whitespace',
    description: 'Cleans up whitespace in attribute values',
    defaultEnabled: true,
    category: 'styles',
  },
  {
    name: 'mergeStyles',
    label: 'Merge styles',
    description: 'Merges multiple <style> elements into one',
    defaultEnabled: true,
    category: 'styles',
  },
  {
    name: 'inlineStyles',
    label: 'Inline styles',
    description: 'Moves style properties to presentation attributes',
    defaultEnabled: true,
    category: 'styles',
  },
  {
    name: 'minifyStyles',
    label: 'Minify styles',
    description: 'Minifies CSS in <style> elements and style attributes',
    defaultEnabled: true,
    category: 'styles',
  },
  {
    name: 'convertStyleToAttrs',
    label: 'Style to attributes',
    description: 'Converts CSS style properties to presentation attributes',
    defaultEnabled: false,
    category: 'styles',
  },
  {
    name: 'removeStyleElement',
    label: 'Remove style elements',
    description: 'Removes <style> elements',
    defaultEnabled: false,
    category: 'styles',
  },

  // IDs & references
  {
    name: 'cleanupIds',
    label: 'Clean up IDs',
    description: 'Removes unused IDs and minifies used ones',
    defaultEnabled: true,
    category: 'ids',
  },
  {
    name: 'removeUselessDefs',
    label: 'Remove unused defs',
    description: 'Removes elements in <defs> that are not used',
    defaultEnabled: true,
    category: 'ids',
  },
  {
    name: 'reusePaths',
    label: 'Replace duplicate elements with links',
    description: 'Replaces duplicate path data with <use> references',
    defaultEnabled: false,
    category: 'ids',
  },
  {
    name: 'removeXlink',
    label: 'Replace xlink with native SVG',
    description: 'Replaces deprecated xlink:href with href',
    defaultEnabled: false,
    category: 'ids',
  },

  // Colors
  {
    name: 'convertColors',
    label: 'Minify colours',
    description: 'Converts colors to shorter representations',
    defaultEnabled: true,
    category: 'colors',
  },
  {
    name: 'convertOneStopGradients',
    label: 'Convert one-stop gradients to solid colours',
    description: 'Converts gradients with a single stop to a plain color',
    defaultEnabled: false,
    category: 'colors',
  },
  {
    name: 'convertColorsToCurrentColor',
    label: 'Apply currentColor',
    description: 'Replaces fill/stroke color values with currentColor (useful for monochrome icons)',
    defaultEnabled: false,
    category: 'colors',
    custom: true,
  },

  // Numbers & paths
  {
    name: 'cleanupNumericValues',
    label: 'Round/rewrite numbers',
    description: 'Round/truncate numeric values',
    defaultEnabled: true,
    category: 'numbers',
  },
  {
    name: 'cleanupListOfValues',
    label: 'Round/rewrite number lists',
    description: 'Rounds numeric values in list attributes like viewBox and points',
    defaultEnabled: false,
    category: 'numbers',
  },
  {
    name: 'convertPathData',
    label: 'Round/rewrite paths',
    description: 'Optimizes path data: rounds values, removes redundant commands',
    defaultEnabled: true,
    category: 'numbers',
  },
  {
    name: 'convertTransform',
    label: 'Round/rewrite transforms',
    description: 'Collapses and optimizes transform attributes',
    defaultEnabled: true,
    category: 'numbers',
  },

  // Shapes & structure
  {
    name: 'convertShapeToPath',
    label: 'Shapes to (smaller) paths',
    description: 'Converts basic shapes to <path> elements when smaller',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'convertEllipseToCircle',
    label: 'Convert non-eccentric <ellipse> to <circle>',
    description: 'Converts ellipses with equal radii to circles',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'mergePaths',
    label: 'Merge paths',
    description: 'Merges multiple paths into one when possible',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'collapseGroups',
    label: 'Collapse useless groups',
    description: 'Removes groups that have no useful attributes',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'moveElemsAttrsToGroup',
    label: 'Move attrs to parent group',
    description: 'Moves common attributes from child elements to their parent group',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'moveGroupAttrsToElems',
    label: 'Move group attrs to elements',
    description: 'Moves presentation attributes from groups to children when better',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'removeNonInheritableGroupAttrs',
    label: 'Remove unneeded group attrs',
    description: 'Removes non-inheritable presentation attributes from groups',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'removeUnknownsAndDefaults',
    label: 'Remove unknowns & defaults',
    description: 'Removes unknown elements, attributes, and default values',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'removeUselessStrokeAndFill',
    label: 'Remove useless stroke & fill',
    description: 'Removes useless stroke and fill attributes',
    defaultEnabled: true,
    category: 'shapes',
  },
  {
    name: 'cleanupEnableBackground',
    label: 'Remove/tidy enable-background',
    description: 'Removes or cleans up enable-background attribute',
    defaultEnabled: true,
    category: 'shapes',
  },

  // Dimensions & viewport
  {
    name: 'removeDimensions',
    label: 'Prefer viewBox to width/height',
    description: 'Removes width/height in favor of viewBox',
    defaultEnabled: false,
    category: 'dimensions',
  },
  {
    name: 'removeViewBox',
    label: 'Remove viewBox',
    description: 'Removes the viewBox attribute when it matches width/height',
    defaultEnabled: false,
    category: 'dimensions',
  },
  {
    name: 'removeOffCanvasPaths',
    label: 'Remove out-of-bounds paths',
    description: 'Removes path elements that are outside the viewport',
    defaultEnabled: false,
    category: 'dimensions',
  },

  // Content removal
  {
    name: 'removeTitle',
    label: 'Remove <title>',
    description: 'Removes <title> elements',
    defaultEnabled: false,
    category: 'content',
  },
  {
    name: 'removeDesc',
    label: 'Remove <desc>',
    description: 'Removes <desc> elements (non-meaningful descriptions only by default)',
    defaultEnabled: true,
    category: 'content',
  },
  {
    name: 'removeHiddenElems',
    label: 'Remove hidden elements',
    description: 'Removes non-visible elements',
    defaultEnabled: true,
    category: 'content',
  },
  {
    name: 'removeEmptyText',
    label: 'Remove empty text',
    description: 'Removes empty text elements',
    defaultEnabled: true,
    category: 'content',
  },
  {
    name: 'removeEmptyAttrs',
    label: 'Remove empty attrs',
    description: 'Removes attributes with empty values',
    defaultEnabled: true,
    category: 'content',
  },
  {
    name: 'removeEmptyContainers',
    label: 'Remove empty containers',
    description: 'Removes empty container elements',
    defaultEnabled: true,
    category: 'content',
  },
  {
    name: 'removeRasterImages',
    label: 'Remove raster images',
    description: 'Removes raster images embedded in SVG',
    defaultEnabled: false,
    category: 'content',
  },
  {
    name: 'removeScripts',
    label: 'Remove scripts',
    description: 'Removes <script> elements and event handler attributes',
    defaultEnabled: false,
    category: 'content',
  },

  // Output
  {
    name: 'sortAttrs',
    label: 'Sort attrs',
    description: 'Sorts element attributes for better compression',
    defaultEnabled: true,
    category: 'output',
  },
  {
    name: 'sortDefsChildren',
    label: 'Sort children of <defs>',
    description: 'Sorts children of <defs> for better compression',
    defaultEnabled: true,
    category: 'output',
  },
];
